In [2]:
import numpy as np 

CRIAÇÃO DE VETORES ATRAVÉS DE LISTAS

In [3]:
qtd = [12,15,26,24]
valor = [25,56,69,39]

In [4]:
#qtd*valor  # as listas não permitem operações matemáticas entre elas
qtd_ar = np.array(qtd)
valor_ar = np.array(valor)

In [7]:
#Ambas instrucoes 
#qtd*valor #retonrnam ERRO
#qtd_ar*valor_ar


In [8]:
#funções de criações de arrays: arrage():
#np.arange(1,10) # cria um array de 1 a 10
#np.arange(1,20,2) # cria um array de 1 a 20 com passe ou incremento 2, (1,3,5...)
np.arange(1,20,2,dtype = float) # cria um array de 1 a 20 com passe ou incremento 2, (1,3,5...19) de tipos float

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [9]:
#funções de criações de arrays: linspace(): retorna números espaçados de modo uniforme em um intervalo
#linspace(ponto de partida, ponto de parada, qtd de valores)
#np.linspace(1,10,10) # 1 será o intervalo
np.linspace(1,10,4) 

array([ 1.,  4.,  7., 10.])

In [9]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Pacote Random:

In [10]:
#função rand(tamanho)  - cria um array de números aleatórios de 0 a 1 -- tecla shift + tab 
np.random.rand(10)

array([0.61627995, 0.0219192 , 0.16225086, 0.22508282, 0.04578955,
       0.63482783, 0.28972458, 0.42350591, 0.7482001 , 0.67231214])

In [14]:
#função randn(tamanho) - cria um array de números de uma normal  de 0 a 1
np.random.randn(10)

array([ 0.93822218,  0.81669992, -0.09837224, -0.48326911,  0.1935133 ,
       -0.18761328,  0.18580762,  1.64083609,  0.55700018, -1.17264886])

In [11]:
#função randint()
np.random.randint(11) # retorna um número aleatório de 0 a 10

0

In [13]:
np.random.randint(0,100, size = 10) # retorna 10 números aleatórios de 0 a 99

array([18, 50, 99, 10,  5, 93, 44, 63, 59, 37])