In [1]:
import numpy as np

In [2]:
vetor = np.arange(1,11,dtype =int)

In [3]:
vetor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#indexacao de arrays unidimensionais
#vetor[4] # acessa o 5º elemento do vetor
#vetor[2:8] #acessa do 3º ao 8º elemento (atenção, nesse caso a ordem do ultimo elemento coincide com o número do índice  )
#vetor[:8] #acessa do 1º ao 8º elemento
#vetor[5:] #acessa do 6º ao ultimo elemento

5

In [20]:
# vetores bidimensionais
matriz = np.random.randint(10,50,size = (4,4))

In [21]:
matriz

array([[27, 47, 14, 22],
       [16, 10, 33, 18],
       [46, 46, 43, 25],
       [31, 16, 17, 13]])

In [24]:
## matriz[linha][coluna]
matriz[0][0] # 1ª linha, 1ª coluna
#matriz[1][2] # 2ª linha, 3º coluna
#matriz[2][0:2] # 3º linha do 1º ao 2º coluna

27

In [25]:
matriz_2 = np.random.randint(1,101,size =(10,10))

In [26]:
matriz_2

array([[  8,  83,  58,  44,  62,  10,  50,  84,   5,  78],
       [ 36,  48,  77,  91,  17,  66, 100,  42,  16,  95],
       [  1,  72,  65,  83,  95,  84,  31,  55,  27,   5],
       [ 47,  73,  45,  68,  43,  96,  46,  34,  68,  52],
       [ 21,  90,  54,  54,  76,  13,  96,  31,  17,  24],
       [ 24,   2,  71,  18,  41,  74,  51,  76,  47,  32],
       [ 49,  65,  42,  47,  66,  59,  26,  56,  54,  12],
       [ 49,   2,  82,  64,  93,   3,  26,  92, 100,  37],
       [ 36,  51,  65,  60,  90,  83,   9,   2,  53,  19],
       [ 93,  98,   6,  92,  18,  19,  55,  58,  60,  94]])

In [29]:
#matriz[linha,coluna] -- outra forma de acesso
#matriz_2[3,3] # 3º linha e 4º coluna
matriz_2[:3,7:] # 1º a 3º linha, 7ª a ultima coluna (obs: sempre inicia a contagem com 0)

array([[84,  5, 78],
       [42, 16, 95],
       [55, 27,  5]])

In [30]:
#matriz2[[linhas]] # dois colchetes retorna o as linhas
matriz_2[[4,6,8]] # retorna a 5º, a 7º e a 9º coluna

array([[21, 90, 54, 54, 76, 13, 96, 31, 17, 24],
       [49, 65, 42, 47, 66, 59, 26, 56, 54, 12],
       [36, 51, 65, 60, 90, 83,  9,  2, 53, 19]])